### ISSUE TITLE
Request : Mealie port

### ISSUE THREAD

**Issue by idarius** [alexbelgium/hassio-addons#22] opened 2021-07-07 15:00 UTC
Hi, first thanks a lot for all your addons, its really helpful :)
Could you port Mealie as well ?
https://github.com/hay-kot/mealie
It is a Cook recipe organiser, the best one that i found.
Thx a lot !

**Comment by alexbelgium** [comment] 2021-07-07 15:57
Hi! I've created one. Could you please check if it works? thanks!

**Comment by alexbelgium** [comment] 2021-07-07 18:28
V2 should fix the absence of webui

**Comment by alexbelgium** [comment] 2021-07-07 18:38
It looks nice! Thanks for making me discover this!

**Comment by alexbelgium** [comment] 2021-07-07 19:11
Mmh it doesn't keep the recipes upon reboot

**Comment by idarius** [comment] 2021-07-07 19:30
Thx à lot for your réactivity !
Same for me, recipe and account setting are not keeped after à reboot

**Comment by idarius** [comment] 2021-07-07 20:07
Updated to 0.5.1-v3 : seems to have fixed the persistant issue, account and recipe are saved between reboot, good job ;)
Is there a way to make this addon compatible with Ingress, in order to work within HA with nabu casa outside my network ?
(i don't know how hard or possible it is, sorry for that :p)

Already more than happy with what i got, time to fill recipes ;)

**Comment by alexbelgium** [comment] 2021-07-07 20:10
Hi, solved in v4 :)
Please let me know if it works!

**Comment by alexbelgium** [comment] 2021-07-07 20:11
For Ingress... I'll have to test in a couple weeks I'm sorry I don't have much time for the moment

**Comment by idarius** [comment] 2021-07-07 20:15
no worries, its already wonderfull to put this up in an hour ;)
Thanks again and have a good day !

**Comment by alexbelgium** [comment] 2021-07-07 20:53
Thanks!

**Comment by alexbelgium** [comment] 2021-07-28 17:04
Mmh... This is much more complicated that I thought. I've spent some time tinkering but can't get it to work yet. The image implements its own reverse proxy, Caddy, but it seems that some elements are hardcoded so ingress doesn't connect. I've had some success with nginx, but then the api can't connect...

**Comment by alexbelgium** [comment] 2021-07-29 14:14
pretty sure it won't work : all url are hard coded such as "/api/", which means that it goes to http://HAurl:8123/api instead of going to the ingress url... so unless someone knows how to rewrite url with the reverse proxy it won't work. sorry.

**Comment by idarius** [comment] 2021-07-29 14:22
Hello, i tried too but not as far as you. Thx for trying, i Could use wireguard or some vpn to resolve This. Thx again !

**Comment by alexbelgium** [comment] 2021-07-29 14:27
well I think we're not too much of too to find a solution ;-) I've commented in the Mealie github but there doesn't seem to be an easy solution... the easiest would be to expose the Mealie port in your router and connect directly to it.

**Comment by idarius** [comment] 2021-07-29 14:44
Of course but i dont have any open port on m'y server beside nabu casa, and dont want to :p i dont really use mealie outside m'y home for now so it Will stay This way for now.

**Comment by alexbelgium** [comment] 2021-07-29 15:26
An url rewrite might do the trick but I don't know how to write it for Caddy reverse proxy

**Comment by alexbelgium** [comment] 2021-08-02 08:28
The creator of Mealie had confirmed that it is not possible to assign a variable path for API, required for ingress. I'll close this as this is not feasible due to the app design...

**Closed by alexbelgium** 2021-08-02 08:28 UTC
Labels: enhancement, wontfix

**Comment by GrandMoff100** [comment] 2021-12-05 20:45
Is there a way to have Mealie show up in the sidebar?

**Comment by alexbelgium** [comment] 2021-12-05 21:38
No, sorry, the app creator had confirmed that it needs a hard coded url which is not compatible with HA ingress...
