### ISSUE TITLE
Request: PhotoPrism - photogallery

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#25] opened 2021-07-10 14:24 UTC
Hi, 

Thank you again for all the created addons in your repo. 
Using many of them :)

But i wonder if you could Photoprism as well? 
I tried Piwigo but it lacks support for videos recorded with camera.

**Links:**
https://docs.photoprism.org/
https://demo.photoprism.org/browse
https://github.com/photoprism/photoprism/

"PhotoPrism is a privately hosted app for browsing, organizing, and sharing your photo collection"

**Comment by alexbelgium** [comment] 2021-07-10 15:13
Hi, thanks for the proposal! I'll look at it in 3 weeks when I'm back with my computer.

Best regards

**Comment by deku-m** [comment] 2021-07-10 15:27
> 
> 
> Hi, thanks for the proposal! I'll look at it in 3 weeks when I'm back with my computer.
> 
> Best regards

No thank you :) enjoy the holiday haha

**Comment by alexbelgium** [comment] 2021-07-25 16:57
Mmh the images are very big... I won't be able to test it on my rpi3b and it risks crashing on build on your system. But if you accept the risk I'll try :)

**Comment by ElVit** [comment] 2021-07-25 17:12
Hi, I am also interested in this addon.  
I have Home Assistant (Hassos) running on an Intel NUC with enough disk space. If you tell me where I can download the addon I would try it. How big will the addon be?

**Comment by alexbelgium** [comment] 2021-07-25 17:21
> Hi, I am also interested in this addon.
> I have Home Assistant (Hassos) running on an Intel NUC with enough disk space. If you tell me where I can download the addon I would try it. How big will the addon be?

That would be great! The addon would be around 800 Mo to 1 Go I believe. That's the size of the dockerhub image, and my addons are wrapper around images developed by other people, usually the linuxserver team or the software developer. 

The addon doesn't exist yet I'll do it in the next days

**Comment by alexbelgium** [comment] 2021-07-26 11:33
Hi, I've pushed a first version on my test repo https://github.com/alexbelgium/hassio-addons-test

As I mentioned, I can't build it on my system as I don't have enough ram for the build. Could you please test it on yours? Before doing the first build, a quick snapshot can't hurt ;-) But if it crashes on build, just reboot your system and everything should be fine again, there is no reason for additional issues.

I've based it on the preview docker images, as it supports arm also, compared to the stable images that only support amd64. However for x64 it should be the same image.

Thanks!

**Comment by alexbelgium** [comment] 2021-07-26 11:35
Btw - this is a test version. The admin password is hard coded to "please_change_password".
Also I haven't configured the data folder yet so there is a probability that changes that you make in the addon, if it boots, aren't remanent. However, already booting is what we aim for!

**Comment by deku-m** [comment] 2021-07-27 06:19
@alexbelgium

Getting the following error:
`The command '/bin/sh -c mkdir -p /tmp/bashio && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz" | tar -xzf - --strip 1 -C /tmp/bashio && mv /tmp/bashio/lib /usr/lib/bashio && ln -s /usr/lib/bashio/bashio /usr/bin/bashio && rm -rf /tmp/bashio /var/{cache,log}/* /var/lib/apt/lists/* RUN mkdir -m 777 -p /data/photoprism/originals /data/photoprism/import /data/photoprism/storage/config /data/photoprism/backup /data/photoprism/storage/cache && chown -Rf photoprism:photoprism /data/photoprism && chmod -Rf a+rwx /data/photoprism && chmod 777 /run.sh' returned a non-zero code: 2`

**Comment by alexbelgium** [comment] 2021-07-31 07:03
Mmh I've pushed a new version and corrected dockerfile. Could you please test if it installs? Thanks!

**Comment by alexbelgium** [comment] 2021-07-31 07:54
At least it installs and boots on my system :)

**Comment by alexbelgium** [comment] 2021-07-31 08:01
MINIMUM CONFIG REQUIRED : 2 cores and 4 GB of memory

**Comment by alexbelgium** [comment] 2021-07-31 08:27
as it builds, I've moved it from the test repo to the normal repo. However it crashes on run on my system as it requires a min of 4fb or RAM, so any feedback would be great :-)

**Comment by deku-m** [comment] 2021-07-31 09:38
I will test it. Never knew the image needed that requirements could have add it xD

**Comment by alexbelgium** [comment] 2021-07-31 09:40
Thanks! Actually I read it from the photoprism documentation here : https://docs.photoprism.org/getting-started/

So I'm,ot certain you NEED 4gb, but what is sure is that it seems resources intensive...

**Comment by deku-m** [comment] 2021-07-31 21:08
It is working for me btw did you build it with the raspberry docker image?
https://docs.photoprism.org/getting-started/raspberry-pi/

I still need to figure out where the photos are stored in the app xD

**Comment by alexbelgium** [comment] 2021-07-31 21:16
Great! The addon is based on the preview image, which supports armv7, arm64 and amd64...

For the storage location, I've set it in the internal /data of the app... Could you please do a few test : import some pictures, try to remove one, restart the addon, and check everything is still there.

If all those work, the addon works officially! And I can easily change the default folders we just need to see what makes the most sense... Or even better I could expose the config folder to allow manual modification...

**Comment by ElVit** [comment] 2021-08-01 06:27
Hi,
Thanks @alexbelgium, the addon is working for me too. 
As @deku-m said it would be nice to see the stored photos in a Home Assistant directory. Maybe somewhere in the 'share' folder?

**Comment by ElVit** [comment] 2021-08-01 06:50
I can add photos and videos. But it seems that deleting is a paid feature for now 🙁 [Link](https://docs.photoprism.org/user-guide/organize/delete/)

**Comment by alexbelgium** [comment] 2021-08-01 17:39
Here it is : you can know configure the folders from the addon options! Please let me know if everything works as intended. Thanks!

**Comment by deku-m** [comment] 2021-08-01 17:52
@alexbelgium 
Think something went wrong
[19:49:51] INFO: Mounting smb share(s)...
[19:49:51] INFO: ... //192.168.1.25/NAS successfully mounted to /mnt/NAS with options 
/run.sh: line 137: CUSTOMOPTIONS: unbound variable

**Comment by alexbelgium** [comment] 2021-08-01 18:56
Thanks! It's corrected. I've updated the readme : now config can be done from the options but any custom flags can be added in the custom options tag. All flags are described here : https://docs.photoprism.org/getting-started/config-options/

Have fun! :)

**Comment by alexbelgium** [comment] 2021-08-02 07:23
Could you please confirm everything is working correctly ? If yes I'll close this request. Thanks!

**Comment by ElVit** [comment] 2021-08-02 08:09
For me it's working again now. Thanks😃
And I found out how to delete photos. 
Go to /share/photoprism/storage/config/settings.yml
Change under "Features" the Option "Delete" to true. 
Restart the addon. 
To delete a photo it must first be archived and can then be deleted in the archived section.

**Comment by alexbelgium** [comment] 2021-08-02 08:25
Thanks for the feedback! Have fun with the addon!

**Closed by alexbelgium** 2021-08-02 08:25 UTC
Labels: enhancement
