### ISSUE TITLE
🐛 [enedisgateway2mqtt] addon crashes during startup if the location of config.yaml is changed

### ISSUE THREAD

**Issue by chrsc59** [alexbelgium/hassio-addons#654] opened 2023-01-21 17:39 UTC
As per [this comment](https://github.com/m4dm4rtig4n/myelectricaldata/issues/282#issuecomment-1399290999), I need to open a case here 

**Which addon?**

- Addon name : enedisgateway2mqtt / myelectricaldata
- Addon version :  Add-on version: 0.8.13-beta1 /  You are running the latest version of this add-on.

**Describe the bug**

addon crashes during startup if the location of config.yaml is changed

**To Reproduce**

1. move `config.yaml` to a custom folder, or simply rename the folder `/config/enedisgateway2mqtt` (`/config/myelectricaldata` for example)
2. Configure the addon in the UI (or yaml edit in the UI) with the new path
3. Start the addon
4. the addon crashes with ``FileNotFoundError: [Errno 2] No such file or directory: '/data/config.yaml'``

**Full addon log**

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.8.13-beta1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION=******
TZ=******
mqtt_autodiscover=******
verbose=******
/etc/cont-init.d/01-custom_script.sh: executing
[18:49:59] INFO: Execute /config/addons_autoscripts/enedisgateway2mqtt.sh if existing
[18:49:59] INFO: ... no script found
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
[18:49:59] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery...
[18:49:59] INFO: ... MQTT service found, fetching server detail (you can enter those manually in your config file) ...
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 2
/etc/cont-init.d/99-run.sh: executing
creating symlink
[18:49:59] INFO: Using database file found in /config/myelectricaldata
[18:49:59] INFO: Using config file found in /config/myelectricaldata/config.yaml
Config file is a valid yaml
 
 
[18:49:59] INFO: Starting the app
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2023-01-20 18:50:01.969 -     INFO :  Configure Databases
2023-01-20 18:50:02.000 -     INFO :   => day
2023-01-20 18:50:02.004 -     INFO :   => call_number
2023-01-20 18:50:02.006 -     INFO :   => max_call
2023-01-20 18:50:02.014 -     INFO :   => version
2023-01-20 18:50:02.016 -     INFO :   => lock
2023-01-20 18:50:02.018 -     INFO :   => lastUpdate
2023-01-20 18:50:02.019 -     INFO :   Success
2023-01-20 18:50:02.522 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-20 18:50:02.523 -     INFO :  RUN IN PRODUCTION MODE
2023-01-20 18:50:02.523 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/main.py", line 31, in <module>
    CONFIG.load()
  File "/app/models/config.py", line 121, in load
    f = open(config_file, "a")
FileNotFoundError: [Errno 2] No such file or directory: '/data/config.yaml'
[18:50:02] FATAL: The app has crashed. Are you sure you entered the correct config options?
```

**Full addon config**

```
cycle: 14400
debug: false
home_assistant:
  discovery_prefix: myelectricaldata
  enable: true
influxdb:
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  username: mqtt_dev
  password: mqtt_dev_password
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
myelectricaldata:
  0123456789:
    enable: true
    name: myTown
    token: azertyuiop
    activation_date_daily: ''
    activation_date_detail: ''
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: '0.1740'
    consumption_price_hc: 0
    consumption_price_hp: 0
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0
    refresh_addresse: false
    refresh_contract: false
```
**System**

 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
---------------------------------------------------

Moving the config file to the initial directory workarounds the problem, and the addon can start

**Comment by chrsc59** [comment] 2023-01-23 07:41
in addition, if the filename is changed i.e. config.yaml -> myelectricaldata.yaml, the addon finds it on startup, but does not use it, it recreates and uses a (default, unconfigured) config.yaml file.

**Comment by alexbelgium** [comment] 2023-01-23 08:48
Hi, that's normal : it only looks for the config.yaml file. However, location should be able to be changed. 

Regarding the location change, watch out that /data/config.yaml is internal to the addon, is that on purpose? As this means that it would create the file in the addon and that you can't access it in a normal HA setting

**Comment by chrsc59** [comment] 2023-01-23 09:10
> Hi, that's normal : it only looks for the config.yaml file. 
fair enough

> Regarding the location change, watch out that /data/config.yaml is internal to the addon, is that on purpose? As this means that it would create the file in the addon and that you can't access it in a normal HA setting

/data/config.yaml is a path that appears in the log from the addon, the path that I used in the addon configuration appears at the beginning of the log : 
```
[18:49:59] INFO: Using database file found in /config/myelectricaldata
[18:49:59] INFO: Using config file found in /config/myelectricaldata/config.yaml
Config file is a valid yaml
```

**Comment by alexbelgium** [comment] 2023-01-23 09:19
Actually, the addons looks like for the file referenced in the addon option, than makes a symlink to /data/config.yaml

[So it is the ](https://github.com/alexbelgium/hassio-addons/blob/81d942e7982937d1c222f65a326ac5c219091147/enedisgateway2mqtt/rootfs/etc/cont-init.d/99-run.sh#L16-L20)

Therefore, you should be able to put the file wherever you want except for /data/config.yaml

I can't test myself as I don't have an ENEDIS account but in theory this should work

**Comment by chrsc59** [comment] 2023-01-23 09:51
> in theory this should work

Well, it does not

**Comment by chrsc59** [comment] 2023-01-23 16:59
It looks like Add-on version: 0.8.13-2 resolved the problem.
Home Assistant proposed to update, so I did, however, I cannof find any reference to this version in this repository nor in the myelectricaldata one.

**Comment by alexbelgium** [comment] 2023-01-24 08:22
Great to read the problem is solved. I'll close this then

**Closed by alexbelgium** 2023-01-24 08:22 UTC
Labels: bug
