### ISSUE TITLE
[Qbittorrent] random ovpn is NOT used as advertised in changelog

### ISSUE THREAD

**Issue by Stooovie** [alexbelgium/hassio-addons#1151] opened 2023-12-30 13:22 UTC
### Description

4.6.2_29 states in the changelog

`Feat : if no ovpn is referred in the option, it will use a random one from the openvpn folder (from https://github.com/Trigus42/alpine-qbittorrentvpn)`

but that's not the case 
![IMG_8097](https://github.com/alexbelgium/hassio-addons/assets/10572373/ad6b5430-8479-4991-94b8-48c32588879a)
![IMG_8096](https://github.com/alexbelgium/hassio-addons/assets/10572373/36ee683b-d72d-40bd-ad8e-52d19f67bee5)
![IMG_8098](https://github.com/alexbelgium/hassio-addons/assets/10572373/777ac287-9ddf-47a2-ae0c-3b1cfc43ad98)

In fact it doesn't work even with config.ovpn in the addons_config folder. Apparently due to the log the file is now expected in /etc/openvpn? Has it moved again?

### Reproduction steps

```bash
1) have ovpn file with different name than config.ovpn
```

### Addon Logs

```bash
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
Use --help for more information.
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/config.ovpn
```

**Comment by alexbelgium** [comment] 2023-12-30 16:49
Hi, thanks! Indeed it seems there was an issue in the code checking if the folder contained *.ovpn files. I've fixed it.

Regarding your second point, the "/etc/openvpn/config.ovpn" is a relicate from an old way of working : the ovpn file is copied from its location to /etc/openvpn before it is modified so it doesn't affect the initial file... Actually I'll probably change that as it can be confusing for the users

**Comment by alexbelgium** [comment] 2023-12-30 18:25
Duplicate of https://github.com/alexbelgium/hassio-addons/issues/1150#issuecomment-1872550737

**Closed by alexbelgium** 2023-12-30 18:25 UTC
Labels: bug
