### ISSUE TITLE
Scrutiny blocked device sda1

### ISSUE THREAD

**Issue by ElVit** [alexbelgium/hassio-addons#10] opened 2021-03-02 14:40 UTC
Hi alexbelguim,

thank you for providing the new addon scrutiny :)
I know its a very new addon, but maybe you can help me with this problem.

I get the following error in supervisor:
`21-03-02 14:27:42 ERROR (SyncWorker_2) [supervisor.docker.addon] Add-on Scrutiny try to access to blocked device sda1!`

If I try to access the Web UI I get only a blank page.
I have only one SSD drive in my Intel NUC.
Do you now how to fix this issue?

Thanks.

**Comment by alexbelgium** [comment] 2021-03-02 15:41
Hi, the webUI can take some time to initialize. Just to better understand, did you remove the "protected mode" flag in the configuration before running ? Have you waited a minute or two to see if webUI initializes?

**Comment by ElVit** [comment] 2021-03-02 16:49
Yes the Protection mode is disabled.
And yes I have waited some time but I don't know how the logs should look like to see that the addon is fully initialized.
But even after some hours the Web UI is blank.

My log looks like this:  
```
       "flags": {
              "value": 192,
              "string": "V--- ",
              "valid": true,
              "normalized": false,
              "supports_dsn": false,
              "monitored_condition_met": false
            }
          },
          {
            "offset": 40,
            "name": "Logical Sectors Read",
            "size": 6,
            "value": 8853530715,
            "flags": {
              "value": 192,
              "string": "V--- ",
              "valid": true,
              "normalized": false,
              "supports_dsn": false,
              "monitored_condition_met": false
            }
          },
          {
            "offset": 48,
            "name": "Number of Read Commands",
            "size": 6,
            "value": 29364737,
            "flags": {
              "value": 192,
              "string": "V--- ",
              "valid": true,
              "normalized": false,
              "supports_dsn": false,
              "monitored_condition_met": false
            }
          }
        ]
      },
      {
        "number": 7,
        "name": "Solid State Device Statistics",
        "revision": 1,
        "table": [
          {
            "offset": 8,
            "name": "Percentage Used Endurance Indicator",
            "size": 1,
            "value": 0,
            "flags": {
              "value": 224,
              "string": "VN-- ",
              "valid": true,
              "normalized": true,
              "supports_dsn": false,
              "monitored_condition_met": false
            }
          }
        ]
      }
    ]
  },
  "sata_phy_event_counters": {
    "table": [
      {
        "id": 1,
        "name": "Command failed due to ICRC error",
        "size": 4,
        "value": 0,
        "overflow": false
      },
      {
        "id": 2,
        "name": "R_ERR response for data FIS",
        "size": 4,
        "value": 0,
        "overflow": false
      },
      {
        "id": 5,
        "name": "R_ERR response for non-data FIS",
        "size": 4,
        "value": 0,
        "overflow": false
      },
      {
        "id": 10,
        "name": "Device-to-host register FISes sent due to a COMRESET",
        "size": 4,
        "value": 8,
        "overflow": false
      }
    ],
    "reset": false
  }
}
time="2021-03-02T16:48:38+01:00" level=info msg="Publishing smartctl results for 0x5001b448b18b03bd\n" type=metrics
time="2021-03-02T16:48:38+01:00" level=info msg="127.0.0.1 - db21ed7f-scrutiny [02/Mar/2021:16:48:38 +0100] \"POST /api/device/0x5001b448b18b03bd/smart\" 200 16 \"\" \"Go-http-client/1.1\" (15ms)" clientIP=127.0.0.1 hostname=db21ed7f-scrutiny latency=15 method=POST path=/api/device/0x5001b448b18b03bd/smart referer= respLength=16 statusCode=200 userAgent=Go-http-client/1.1
time="2021-03-02T16:48:38+01:00" level=info msg="Main: Completed" type=metrics
[16:48:38] INFO: Local Devices Added
```

**Comment by alexbelgium** [comment] 2021-03-02 20:57
Thanks I'll look into that as soon as I find some time... Perhaps some apparmor setting that I need to tweak

**Comment by alexbelgium** [comment] 2021-03-07 09:48
Hi, could you please test dev2? It could have solved the issue. Thanks!

**Comment by ElVit** [comment] 2021-03-10 19:58
@alexbelgium 
No still not working :(
I'm using now the version 27b923b5-ls11

**Comment by alexbelgium** [comment] 2021-03-10 20:14
Actually your log is normal it just shows that the sda1 device is present and has Smart data. I don't see why the ui wouldn't be visible. I've noticed that the ui is not visible on some smartphone browsers sur as Microsoft Edge and results in a white screen. Is that what you got? Or do you have just an error message as if the page didn't exist?

**Comment by alexbelgium** [comment] 2021-03-11 05:44
Actually the developer is aware of the issue. Here is the link : https://github.com/AnalogJ/scrutiny/issues/92

As the issue is with the upstream image I'll close the issue of you confirm it works with desktop view

**Closed** 2021-03-11 05:47 UTC

**Comment by ElVit** [comment] 2021-03-11 08:15
@alexbelgium 
Oh yes you are right. 
It is working on my windows pc :)
But if I change to desktop mode in iOS safari it sill doesn't work, maybe a safari issue...

Thanks for the link to the original scrutiny issue.
