### ISSUE TITLE
Nextcloud Upload limit

### ISSUE THREAD

**Issue by rjgout** [alexbelgium/hassio-addons#117] opened 2021-12-16 11:04 UTC
Hi, where can I find the files to change the upload limit?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

I cna't find the config file like the other dockers.

And is it possible to mount a share where the files will be stored?

**Comment by alexbelgium** [comment] 2021-12-16 14:27
Hi,
Here is the current limits : 
	-e 's/memory_limit.*=.*128M/memory_limit=512M/g' \
	-e 's/max_execution_time.*=.*30/max_execution_time=120/g' \
	-e 's/upload_max_filesize.*=.*2M/upload_max_filesize=1024M/g' \
	-e 's/post_max_size.*=.*8M/post_max_size=1024M/g' \

What values would you like? I can change the addons (the file is not accessible otherwise)

For external storage, everything is taken into account natively in the app : https://docs.nextcloud.com/server/19/admin_manual/configuration_files/external_storage_configuration_gui.html

Best regards

**Comment by rjgout** [comment] 2021-12-16 14:33
Nice, thanks for the url. 
I would like to be able to upload 25GB

**Comment by alexbelgium** [comment] 2021-12-16 15:12
A file of 25gb? Limits size are per file

**Comment by rjgout** [comment] 2021-12-16 15:33
4K movie? I want to transfer a database. So for now 10GB would also be fine.

**Comment by alexbelgium** [comment] 2021-12-16 16:10
ok I'll do that, let's try this! It'll be in the new version I'll push now

**Comment by rjgout** [comment] 2021-12-16 17:26
The change seems to be made. But it looks like it is not working. As if there is another setting to be changed.

**Comment by alexbelgium** [comment] 2021-12-16 18:08
I've pushed a new version but not sure about the cause

**Comment by rjgout** [comment] 2021-12-18 09:52
Still not working. Maybe the nginx setting?

**Comment by alexbelgium** [comment] 2021-12-18 17:28
Thanks for the report, I'll have a further look and indeed at the nginx config.

Is this large size upload a recurrent thing, or is it a one time upload that could be managed through another way (like direct access to the disk)?

**Comment by alexbelgium** [comment] 2021-12-18 18:22
A new version 23.0.0-5 is pushed, could you please test what is the highest amount you can upload? Not exact of course but perhaps check if some large files (>1 go) still upload?

Thanks!

**Comment by rjgout** [comment] 2021-12-18 18:34
It will be under the 2GB. A but over and it fails.

**Comment by alexbelgium** [comment] 2021-12-18 18:35
Strange... As it still is a quite high value, well above the nginx defaults. I'll investigate a bit more

**Comment by alexbelgium** [comment] 2021-12-18 18:37
According to this, could you please try to disable encryption? https://help.nextcloud.com/t/cant-get-past-2-gb-upload-limit/59622

**Comment by rjgout** [comment] 2021-12-18 18:54
It does not even start the upload with me. Maybe it could be this? https://help.nextcloud.com/t/difference-between-plain-vs-docker-version-in-view-of-2gb-file-size-limit/99547/3

**Comment by alexbelgium** [comment] 2021-12-18 19:18
Do you have a 64bit system? If 32, that could be the issue. It doesn't necessarly depend on the device, as you can install 32 bits HA on a 64 bits architecture.

Sincerely I wonder if a tool like syncthing wouldn't be more fit for your usage.

I'll still continue to investigate a bit

**Comment by rjgout** [comment] 2021-12-18 19:23
## System Health

version | core-2021.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.18.0
Stage | running
Available Repositories | 923
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 62.3 GB
disk_used | 49.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.9.0), Z-Wave JS (0.1.50), Samba share (9.5.1), Mosquitto broker (6.0.1), InfluxDB (4.3.0), Grafana (7.4.0), Nginx Proxy Manager (0.11.0), MariaDB (2.4.0), UniFi Network Application (1.1.3), TimescaleDB (1.1.6), DSMR Reader (0.7.0), Home Assistant Google Drive Backup (0.105.2), Tautulli (2.3.0), AdGuard Home (4.2.0), Studio Code Server (3.7.0), WireGuard (0.6.0), Xteve (2.2.0.200), Radarr NAS (3.2.2.5080-5), Lidarr NAS (0.8.1.2135-ls63-4), Bazarr NAS (1.0.1), Ombi (4.3.3-2), Sonarr NAS (3.0.6.1342-4), Prowlarr NAS (nightly-0.1.8.1259-ls230), Ubooquity (2.1.2-8), Nextcloud (23.0.0-5), readarr NAS (nightly-0.1.0.1137-ls55), readarr NAS (nightly-0.1.0.1137-ls55), Mylar3 (0.6.1), Spotweb (1.0.9), Qbittorrent (14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls160-2), Nzbget (21.1), Portainer (2.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 1
views | 5
mode | storage

</details>

I guess it is 64 bit. I thought maybe the docker image was 32. Ow and the encryption was not even enabled.

**Comment by rjgout** [comment] 2021-12-18 19:25
What I love about Nextcloud is the drop function. The one dropping files does not see the already uploaded files. The files are being droped outside the network.

**Comment by alexbelgium** [comment] 2021-12-18 19:37
Mmh... I've checked another thing (tmp dir) but it doesn't work either... Regarding your device info I don't see actually a confirmation if you run 32or 64 bits HA on your x86_64 system and not sure how to check that... I'll try to look at it again tomorrow

**Comment by rjgout** [comment] 2021-12-18 19:39
Yeah, no hurry. Thanks for all that you do.

**Comment by alexbelgium** [comment] 2021-12-18 21:27
Just realized that only an uninstall refreshed the nginx config that I had modified in the previous version. I've pushed a new version that increases to 10go the mx size through nginx, and added code to update the nginx file without a full uninstall. Could you please update and test? Thanks!

**Comment by alexbelgium** [comment] 2021-12-18 21:45
On addition to update, here is another thing that could help. If you go in nextcloud options, in administration, system tab, you can see the max upload able size

’‘‘‘
PHP

Version : 7.4.26
Limite de mémoire : 512 MB
Temps d’exécution maximal : 3600
Taille de téléversement maximale : 10 GB
‘‘‘

**Comment by rjgout** [comment] 2021-12-18 21:45
Tested it. No success. Even rebooted the complete host.

**Comment by rjgout** [comment] 2021-12-18 21:50
![Uploading A5CD085A-3885-42BD-A78C-0578842058BE.jpeg…]()

**Comment by alexbelgium** [comment] 2021-12-28 09:46
Hi, I've uploaded a 3,8Go file without issue using a VirtualBox system on a 64 bits processor. 

I've checked and the image itself is truly a 64bits : this can be checked by logging in a console using portainer, and typing ```getconf LONG_BIT```. Also, it seems that indeed your system is 64 bits as it is described as x86_64... I'm sorry but it seems that the limitation is on your system and not the addon... For example a FAT data partition, a limitation in your router or network device, a lack of space...

I'll close the issue as I don't really see how I could help you more. However, perhaps people on the nextcloud github could help you
![2021-12-2810_43_10](https://user-images.githubusercontent.com/44178713/147553136-8c0b23be-cdfe-4215-a7d4-b817713c6138.png)
![2021-12-2810_45_58](https://user-images.githubusercontent.com/44178713/147553139-012b22f8-3b21-41a7-8c9a-6e995ee6a1cc.png)
?

**Closed by alexbelgium** 2021-12-28 09:46 UTC
