### ISSUE TITLE
[Qbittorrent] Download save path

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#155] opened 2022-01-11 06:41 UTC
**Which addon?**

* Addon name : Qbittorrent
* Addon version : 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-3 

**Describe the bug**

After last update the torrent save path is configured to config/Downloads and moved all torrent to that folder.
Changing it to mnt/nas/downloads wont help as it keeps changing it back to /config/downloads again.

**To Reproduce**
1. Go to Qbittorrent
2. Click on open settings/Downloads 
3. Scroll down to Saving Management change directory under Default Save Path
4. See error --> After restart you see it changed back to /config/Downloads
5. Result is that all files moved as well.

**Full addon log**

Nothing to find in logging.
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 30-nginx.sh: executing... 
[cont-init.d] 30-nginx.sh: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 90-dns_set.sh: executing... 
[07:39:23] INFO: DNS Servers option empty. Using default router (or HA) dns servers.
[cont-init.d] 90-dns_set.sh: exited 0.
[cont-init.d] 91-qbittorrent_configuration.sh: executing... 
[07:39:23] INFO: Downloads can be found in /mnt/NAS/Downloads/
[07:39:23] INFO: Whitelisted subsets will not require a password : localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
[07:39:23] INFO: WEBUI username set to admin
[07:39:23] INFO: Alternate UI enabled : vuetorrent. If webui don't work, disable this option
[07:39:24] INFO: Default username/password : admin/adminadmin
[07:39:24] INFO: Configuration can be found in /config/qBittorrent
[cont-init.d] 91-qbittorrent_configuration.sh: exited 0.
[cont-init.d] 92-local_mounts.sh: executing... 
[cont-init.d] 92-local_mounts.sh: exited 0.
[cont-init.d] 92-smb_mounts.sh: executing... 
Mounting smb share(s)...
[07:39:24] INFO: ... //192.168.1.25/NAS successfully mounted to /mnt/NAS with options 
[cont-init.d] 92-smb_mounts.sh: exited 0.
[cont-init.d] 93-openvpn.sh: executing... 
[07:39:24] INFO: Direct connection without VPN enabled
[cont-init.d] 93-openvpn.sh: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Full addon config**

ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
whitelist: localhost,127.0.0.1,172.30.0.0/16,192.168.0.0/16
customUI: vuetorrent
SavePath: /mnt/NAS/Downloads/
Username: admin
DNS_server: ''
PUID: '0'
PGID: '0'
TZ: ''
openvpn_enabled: false
openvpn_alternative_mode: false
networkdisks: //192.168.1.25/NAS/
cifspassword: <secret>
cifsusername: Maikel
openvpn_config: <secret>
openvpn_username: <secret>
openvpn_password: <secret>

**System**

* Supervisor version: supervisor-2021.12.2
* Host system version: core-2021.12.9

**Comment by alexbelgium** [comment] 2022-01-11 07:16
Thanks, I've got the same : It's a bug in qbittorrent 4.4.0, I see it is being worked on in the qbittorrent repo. However, does it correctly download to the right place or not?

**Comment by alexbelgium** [comment] 2022-01-11 07:25
I reverted to previous version of qbittorrent and will let it so for a week until a new version of the app is published. Please update it will work again

**Comment by deku-m** [comment] 2022-01-11 07:25
> Thanks, I've got the same : It's a bug in qbittorrent 4.4.0, I see it is being worked on in the qbittorrent repo. However, does it correctly download to the right place or not?
> 
> [qbittorrent/qBittorrent#15969](https://github.com/qbittorrent/qBittorrent/issues/15969)

No as soon as i add a torrent it directly place it in config/downloads. I need to change location myself.

**Comment by alexbelgium** [comment] 2022-01-11 07:39
OK, I'll wait for a new version before pushing again the 4.4.0 app. I'll close this as the issue is solved with the revert I've just made

**Closed** 2022-01-12 06:59 UTC
Labels: bug
